# Generated by Django 5.1.15 on 2026-08-18 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('origin_name', models.CharField(max_length=255)),
                ('pickup_name', models.CharField(max_length=255)),
                ('dropoff_name', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField(default=0.0)),
                ('departure_time', models.CharField(blank=True, max_length=100, null=True)),
                ('total_distance_miles', models.FloatField(default=0.0)),
                ('total_drive_time_hours', models.FloatField(default=0.0)),
                ('total_trip_duration_hours', models.FloatField(default=0.0)),
                ('days_required', models.IntegerField(default=1)),
                ('fuel_stops_count', models.IntegerField(default=0)),
                ('summary_json', models.JSONField(default=dict)),
                ('locations_json', models.JSONField(default=dict)),
                ('route_geometry_json', models.JSONField(default=dict)),
                ('events_json', models.JSONField(default=list)),
                ('turn_by_turn_steps_json', models.JSONField(default=list)),
                ('disclaimers_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_number', models.IntegerField(default=1)),
                ('log_date', models.CharField(max_length=50)),
                ('driver_name', models.CharField(default='Alex Morgan', max_length=150)),
                ('carrier_name', models.CharField(default='MileMint Logistics LLC', max_length=200)),
                ('truck_id', models.CharField(default='TRK-9042', max_length=50)),
                ('total_driving_hours', models.FloatField(default=0.0)),
                ('total_on_duty_hours', models.FloatField(default=0.0)),
                ('total_off_duty_hours', models.FloatField(default=0.0)),
                ('total_sleeper_hours', models.FloatField(default=0.0)),
                ('is_fmcsa_compliant', models.BooleanField(default=True)),
                ('grid_intervals_json', models.JSONField(default=list)),
                ('remarks_json', models.JSONField(default=list)),
                ('recap_json', models.JSONField(default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.trip')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
