# Generated by Django 5.1.15 on 2026-08-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='log_data_json',
            field=models.JSONField(default=dict),
        ),
    ]
